/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo.akademik.view;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.Timer;

/**
 *
 * @author sky
 */
public class MainFrame extends javax.swing.JFrame {

    java.util.Date tglsekarang = new java.util.Date();
    private final SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
    private final String tanggal = smpdtfmt.format(tglsekarang);
    
    public final void setJam(){
        ActionListener taskPerformer = (ActionEvent e) -> {
            String nol_jam = "", nol_menit = "",nol_detik = "";
            java.util.Date dateTime = new java.util.Date();
            int nilai_jam = dateTime.getHours();
            int nilai_menit = dateTime.getMinutes();
            int nilai_detik = dateTime.getSeconds();
            if(nilai_jam <= 9) nol_jam= "0";
            if(nilai_menit <= 9) nol_menit= "0";
            if(nilai_detik <= 9) nol_detik= "0";
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
            lblWaktu.setText(jam+":"+menit+":"+detik+" "+" WIB");
        };
        new Timer(1000, taskPerformer).start();
    }
    
    CardLayout cLayout = new CardLayout();
    panelMahasiswa p1;
    panelJurusan p2;
    
    /**
     * Creates new form MainFrame
     * @throws java.sql.SQLException
     */
    public MainFrame() throws SQLException {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        lblTanggal.setText(tanggal);
        setJam();
        
        p1 = new panelMahasiswa();
        
        PaneMahasiswa.setLayout(cLayout);
        String name = "Panel Mahasiswa";
        PaneMahasiswa.add(p1, name);
        
        p2 = new panelJurusan();
        PaneJurusan.setLayout(cLayout);
        String name2 = "Panel Jurusan";
        PaneJurusan.add(p2, name2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return 
     */
    @SuppressWarnings("unchecked")
    public JTabbedPane getTab(){
        return TabPane;
    }
    
    public  JPanel getPaneJurusan(){
        return PaneJurusan;
    }
    
    public  JPanel getPaneMahasiswa(){
        return PaneMahasiswa;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTanggal = new javax.swing.JLabel();
        lblWaktu = new javax.swing.JLabel();
        TabPane = new javax.swing.JTabbedPane();
        PaneJurusan = new javax.swing.JPanel();
        PaneMahasiswa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTanggal.setText("19 Desember 2016");

        lblWaktu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWaktu.setText("18:30 WIB");

        javax.swing.GroupLayout PaneJurusanLayout = new javax.swing.GroupLayout(PaneJurusan);
        PaneJurusan.setLayout(PaneJurusanLayout);
        PaneJurusanLayout.setHorizontalGroup(
            PaneJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        PaneJurusanLayout.setVerticalGroup(
            PaneJurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        TabPane.addTab("Jurusan", PaneJurusan);

        javax.swing.GroupLayout PaneMahasiswaLayout = new javax.swing.GroupLayout(PaneMahasiswa);
        PaneMahasiswa.setLayout(PaneMahasiswaLayout);
        PaneMahasiswaLayout.setHorizontalGroup(
            PaneMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        PaneMahasiswaLayout.setVerticalGroup(
            PaneMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        TabPane.addTab("Mahasiswa", PaneMahasiswa);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DEMO AKADEMIK DUA TABLE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTanggal)
                .addGap(33, 33, 33)
                .addComponent(lblWaktu)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTanggal)
                    .addComponent(lblWaktu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MainFrame().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneJurusan;
    private javax.swing.JPanel PaneMahasiswa;
    private javax.swing.JTabbedPane TabPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblWaktu;
    // End of variables declaration//GEN-END:variables
}
